### ISSUE TITLE
the Variable flushInterval no assignment

### ISSUE THREAD

**Issue by xiaofateng** [mvalleavila/Kafka-Spark-Hbase-Example#1]
hi,mvalleavila 
   your example  helpful for me.

   I found a probloem the Variable flushInterval no assignment.
   so flushInterval  is 0. 
I wonder this is your intention or just forget to   assignment.

Thks

**Comment by mvalleavila** [comment]
Hello Xiao,

Refreshing my knowledge of the code I think is my intention to use 0 to flush interval, but is an error not to initialize this variable.

Setting it to 0 the flush interval will be 0 so the commits to hBase will be in near-real-time (spark streaming inserts a latency of 200ms)

Hope it's helps

Regards,
Marcelo

**Comment by xiaofateng** [comment]
Hi Marcelo,

 Thanks  for your reply.
 got it.

Regards,
Xiao
